### ISSUE TITLE
Unexpected behavior when serializing 'Maybe' value

### ISSUE THREAD

**Issue by enzoh** [well-typed/cborg#168]
Encoding `Nothing` should really produce a CBOR null value and `Just x` should produce the CBOR value for `x`. Then implement the decoding making `Decoder s` an instance of `Alternative`.

**Comment by adamgundry** [comment]
@enzoh the problem with that encoding is that it doesn't round-trip for `Maybe (Maybe a)`. People run into this with Aeson occasionally when using it to encode JSON, and it's a pain.

If you need to interoperate with a specific external CBOR format, you might be better off using the `cborg` API rather than `serialise` (or you could perhaps create a new type).
