### ISSUE TITLE
Bikeshed the module namespace and some APIs

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/cborg#24]
After a chat with @dcoutts earlier, there could probably be a bit of restructuring done in the package and renaming to make things a bit more fluid and consistent (exposing lazy vs strict interfaces, module hierarchy and module naming, etc).

We'll probably talk a bit more about this later; consider this issue a place holder.

**Comment by adamgundry** [comment]
Just a quick observation from the trenches: it would be useful if the API exposed the "with" variants of `Serialise` instances, e.g.

    encodeListWith :: (a -> Encoding) -> [a] -> Encoding

instead of just

    defaultEncodeList :: Serialise a => [a] -> Encoding

**Comment by dcoutts** [comment]
Probably the `.Class` module should re-export all the useful bits of `.Encoding` and `.Decoding` that are useful for writing class instances. It should also export the class QC properties (which themselves do not depend on QC at all).

**Comment by dcoutts** [comment]
@adamgundry for what use case? For writing instances for sequence-like types?

**Comment by adamgundry** [comment]
Actually, decoding is probably a better example than encoding. I have a decoder that can't (conveniently) be a class instance, because it depends on values being passed in, which describe the generic schema of the CBOR data. But I still want to use the standard encoding/decoding functions for lists. [Here's the relevant code in api-tools](https://github.com/iconnect/api-tools/blob/0.7.0.0/src/Data/API/Value.hs#L243).

**Comment by dcoutts** [comment]
Should also decide on names, encode/decode or serialise/deserialise? The binary package uses get/put and Binary. The cereal package uses get/put and Cereal. The store package uses peek/poke and Store.

**Comment by bgamari** [comment]
Frankly I think the status quo is fine.

**Comment by bgamari** [comment]
I think we can safely close this now since the thing is released.
